amf:
  addr: 139.144.69.203 #The address or hostname of the AMF.
  bind_addr: 192.168.176.84 # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64 # Optionally pass arguments to the selected RF driver.
  clock: # Specify the clock source used by the RF.
  sync: # Specify the sync source used by the RF.
  srate: 23.04 # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 70 # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 50 # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 650000
  band: 78 # The NR band.
  channel_bandwidth_MHz: 20 # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30 # Subcarrier spacing in kHz used for data.
  plmn: "99970"
  tac: 7 # Tracking area code (needs to match the core configuration).
  pci: 321 # Physical cell ID.

log:
  filename: /home/theodor/Documents/TUB/5GSecProject/logs/gnb.log # Path of the log file.
  all_level: warning # Logging level applied to all layers.

pcap:
  mac_enable: false # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap # Path where the MAC PCAP is stored.
  ngap_enable: false # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
